### ISSUE TITLE
CheckMK Memcached.py Crash Report

### ISSUE THREAD

**Issue by 47k** [HeinleinSupport/check_mk_extensions#88]
CheckMK Version is 2.0.0p6 CRE

```
* /omd/sites/test/local/lib/python3/cmk/base/plugins/agent_based/memcached.py

Maybe these files are not compatible with your current Checkmk version. Please verify and only report this crash when you think this should be working.
```

**Exception**: TypeError ('state' must be a checkmk State constant, got 1)

**Traceback:**

```
 File "/omd/sites/test/lib/python3/cmk/base/checking.py", line 582, in get_aggregated_result
    result = _aggregate_results(check_function(**kwargs))
  File "/omd/sites/test/lib/python3/cmk/base/checking.py", line 813, in _aggregate_results
    perfdata, results = _consume_and_dispatch_result_types(subresults)
  File "/omd/sites/test/lib/python3/cmk/base/checking.py", line 857, in _consume_and_dispatch_result_types
    for subr in subresults:
  File "/omd/sites/test/lib/python3/cmk/base/api/agent_based/register/check_plugins.py", line 89, in filtered_generator
    for element in generator(*args, **kwargs):
  File "/omd/sites/test/local/lib/python3/cmk/base/plugins/agent_based/memcached.py", line 208, in check_memcached
    yield Result(state=status,
  File "/omd/sites/test/lib/python3/cmk/base/api/agent_based/checking_classes.py", line 349, in __new__
    state, summary, details = _create_result_fields(**kwargs)
  File "/omd/sites/test/lib/python3/cmk/base/api/agent_based/checking_classes.py", line 375, in _create_result_fields
    raise TypeError(f"'state' must be a checkmk State constant, got {state}")
```

The script output on the server is normal.

**Comment by gurubert** [comment]
This should be fixed with commit 6ff0de9ee1fc5890b333b4b3346f1446d73e20f1 and MKP version 5.3

**Comment by 47k** [comment]
Thank you for your fast reply. Unfortunately I got on me productive and my desting environment issues during the installation:

root@DebianVMWareVM:/home/user# omd su Test
OMD[Test]:~$ mkp list
Radius
imap
kemplb
wsus_sync_status
xen

```
OMD[Test]:~$ mkp install /home/usser/memcached-5.3.mkp
Traceback (most recent call last):
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1674, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1651, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1514, in __init__
    self.firstmember = self.next()
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 2318, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1104, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/omd/sites/Test/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/Test/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/Test/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/Test/lib/python3/cmk/base/modes/check_mk.py", line 654, in mode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/Test/lib/python3/cmk/base/packaging.py", line 89, in do_packaging
    f(args)
  File "/omd/sites/Test/lib/python3/cmk/base/packaging.py", line 288, in package_install
    packaging.install_by_path(path)
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 350, in install_by_path
    return install(file_object=cast(BinaryIO, f))
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 354, in install
    package = _get_package_info_from_package(file_object)
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 485, in _get_package_info_from_package
    tar = tarfile.open(fileobj=file_object, mode="r:gz")
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1621, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1678, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
```

**Comment by gurubert** [comment]
Did you download the raw file or the HTML page?

$ tar tfvz memcached-5.3.mkp
-rw-r--r-- 0/0             994 2021-07-07 11:20 info
-rw-r--r-- 0/0             799 2021-07-07 11:20 info.json
-rw-r--r-- 0/0           20480 2021-07-07 11:20 agent_based.tar
-rw-r--r-- 0/0           10240 2021-07-07 11:20 agents.tar
-rw-r--r-- 0/0           20480 2021-07-07 11:20 web.tar
-rw-r--r-- 0/0           10240 2021-07-07 11:20 lib.tar

**Comment by 47k** [comment]
```
# wget https://github.com/HeinleinSupport/check_mk_extensions/blob/cmk2.0/memcached/memcached-5.3.mkp
memcached-5.3.mkp             [ <=>                               ] 108.25K  --.-KB/s    in 0.06s
2021-07-07 13:39:32 (1.63 MB/s) - ‘memcached-5.3.mkp’ saved [110848]
```

```
# ls -lisah |grep memcached-5.3.mkp
1060202 112K -rw-r--r-- 1 root     root     109K Jul  7 13:39 memcached-5.3.mkp
# tar tfvz memcached-5.3.mkp
```

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by gurubert** [comment]
Please try

    # wget https://github.com/HeinleinSupport/check_mk_extensions/raw/cmk2.0/memcached/memcached-5.3.mkp

**Comment by 47k** [comment]
That worked! Thanks! :) Took some time until the plugin worked again in CheckMK
