### ISSUE TITLE
Any plans to port uname to CMK 2.0 ?

### ISSUE THREAD

**Issue by a-mlbz** [HeinleinSupport/check_mk_extensions#98]
Hey guys,

first of all thanks a lot for providing so many great plugins!

We just upgraded from 1.6 to 2.0.0p19 and noticed that the UNAME plugin is broken when backing new agents:

```
Exception: Error running automation call bake-agents (exit code 2), error: 
Error creating agent for MYSERVER: Error creating agents: Error creating d5070c236894f14e/linux_deb agent for MYSERVER: Error in bakery plugin "uname": name 'shutil' is not defined

Traceback (most recent call last):
  File "/omd/sites/global/lib/python3/cmk/base/cee/bakery/agent_bakery.py", line 430, in _execute_pre_17_bakery_plugin
    bake_func(**func_args)
  File "<string>", line 11, in bake_uname
NameError: name 'shutil' is not defined
.

Error creating d5070c236894f14e/solaris_pkg agent for MYSERVER: Error in bakery plugin "uname": name 'shutil' is not defined

Traceback (most recent call last):
  File "/omd/sites/global/lib/python3/cmk/base/cee/bakery/agent_bakery.py", line 430, in _execute_pre_17_bakery_plugin
    bake_func(**func_args)
  File "<string>", line 11, in bake_uname
NameError: name 'shutil' is not defined
.

Error creating d5070c236894f14e/aix_tgz agent for MYSERVER: Error in bakery plugin "uname": name 'shutil' is not defined

Traceback (most recent call last):
  File "/omd/sites/global/lib/python3/cmk/base/cee/bakery/agent_bakery.py", line 430, in _execute_pre_17_bakery_plugin
    bake_func(**func_args)
  File "<string>", line 11, in bake_uname
NameError: name 'shutil' is not defined
```

Unfortunately I couldnt find it in the 2.0 branch of your plugins. After some research it looks like a port to CMK 2.0.0 is needed. 

Would be awesome if you could migrate it.

Cheers!

**Comment by gurubert** [comment]
> Unfortunately I couldnt find it in the 2.0 branch of your plugins.

This extension has been deprecated. The same information is available with the hardware / software inventory.
